#!/usr/bin/env bash

NET_NAME="postgres"
DNS_IP="10.0.0.72"
WILDFLY_PORT=8080
LOCAL_WILDFLY_PORT=8080
ADMIN_PORT=9990
LOCAL_ADMIN_PORT=9990
POSTGRES_VERSION=9.4.1207
RBAC_VERSION=2.0.4
RBAC_VERSION_REPO=Release-2.0.6
ESS_JAVA_CONFIG_VERSION=2.2.0
WAIT_FOR_IT_VERSION=master

ESS_JAVA_CONFIG_REPO=ess-java-config
WAIT_FOR_IT_REPO=wait-for-it

RBAC_REPO=rbac
RBAC_TARGET_WAR=${RBAC_REPO}/RBAC-AuthServices/target/auth-services-${RBAC_VERSION}.war
