#!/usr/bin/env bash

NET_NAME="postgres"
DNS_IP="10.0.0.72"
WILDFLY_PORT=8443
#LOCAL_WILDFLY_PORT=8443
LOCAL_WILDFLY_PORT=8444
ADMIN_PORT=9990
#LOCAL_ADMIN_PORT=9990
LOCAL_ADMIN_PORT=9991
POSTGRES_VERSION=9.4.1207
#RBAC_VERSION=2.0.4
RBAC_VERSION=2.1.6
RBAC_VERSION_REPO=Release-2.0.6
ESS_JAVA_CONFIG_VERSION=2.2.0
WAIT_FOR_IT_VERSION=master

ESS_JAVA_CONFIG_REPO=ess-java-config
WAIT_FOR_IT_REPO=wait-for-it

#RBAC_SERVICE_PATH=RBAC-AuthServices
#RBAC_SERVICE_NAME=auth-services
#RBAC_DOCKER_IMAGE_NAME=rbac
RBAC_SERVICE_PATH=RBAC-ManagementStudio
RBAC_SERVICE_NAME=management-studio
RBAC_DOCKER_IMAGE_NAME=rbac-management-studio
RBAC_REPO=rbac
RBAC_TARGET_WAR=${RBAC_REPO}/${RBAC_SERVICE_PATH}/target/${RBAC_SERVICE_NAME}-${RBAC_VERSION}.war
