#!/usr/bin/env bash

SERVICE="$1"

RBAC_REPO=rbac

# Default values
LOCAL_WILDFLY_PORT=8443
LOCAL_ADMIN_PORT=9990

RBAC_VERSION=2.0.4
RBAC_SERVICE_PATH=RBAC-AuthServices
RBAC_SERVICE_NAME=auth-services
RBAC_DOCKER_IMAGE_NAME=rbac-auth-services
DB_NAME=rbac-auth-services-postgres
DB_PORT=5432
#NET_NAME="postgres-rbac"
NET_NAME="dockerrbacauthservicescomposed_postgres-rbac"

if [ "${SERVICE}" == "rbac" ]; then
    LOCAL_WILDFLY_PORT=8444
    LOCAL_ADMIN_PORT=9991

    RBAC_VERSION=2.0.4
    RBAC_SERVICE_PATH=RBAC-AuthServices
    RBAC_SERVICE_NAME=auth-services
    RBAC_DOCKER_IMAGE_NAME=rbac-auth-services

    DB_NAME=rbac-auth-services-postgres
    DB_PORT=5432
elif [ "${SERVICE}" == "mgmt" ]; then
    LOCAL_WILDFLY_PORT=8445
    LOCAL_ADMIN_PORT=9992

    RBAC_VERSION=2.1.6
    RBAC_SERVICE_PATH=RBAC-ManagementStudio
    RBAC_SERVICE_NAME=management-studio
    RBAC_DOCKER_IMAGE_NAME=rbac-management-studio

    DB_NAME=rbac-management-studio-postgres
    DB_PORT=5432
else
    echo "Unsupported service"
    exit 0
fi

DNS_IP="10.0.0.72"
WILDFLY_PORT=8443
ADMIN_PORT=9990
POSTGRES_VERSION=9.4.1207
RBAC_VERSION_REPO=Release-2.0.6
ESS_JAVA_CONFIG_VERSION=2.2.0
WAIT_FOR_IT_VERSION=master

ESS_JAVA_CONFIG_REPO=ess-java-config
WAIT_FOR_IT_REPO=wait-for-it

RBAC_CLIENT_API_SERVICE_PATH=RBAC-ClientAccess-Java-API
RBAC_CLIENT_API_SERVICE_NAME=client-access-java-api
RBAC_CLIENT_API_VERSION=2.1.1
RBAC_CLIENT_API_JAR=${RBAC_REPO}/${RBAC_CLIENT_API_SERVICE_PATH}/target/${RBAC_CLIENT_API_SERVICE_NAME}-${RBAC_CLIENT_API_VERSION}.jar

RBAC_DSACCESS_LDAP_SERVICE_PATH=RBAC-DSAccess-LDAP
RBAC_DSACCESS_LDAP_SERVICE_NAME=dsaccess-ldap
RBAC_DSACCESS_LDAP_VERSION=2.1.0
RBAC_DSACCESS_LDAP_JAR=${RBAC_REPO}/${RBAC_DSACCESS_LDAP_SERVICE_PATH}/target/${RBAC_DSACCESS_LDAP_SERVICE_NAME}-${RBAC_DSACCESS_LDAP_VERSION}.jar

RBAC_TARGET_WAR=${RBAC_REPO}/${RBAC_SERVICE_PATH}/target/${RBAC_SERVICE_NAME}-${RBAC_VERSION}.war

